builds:
  - id: default
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -extldflags=-static
      - -X codeberg.org/pixivfe/pixivfe/config.revision={{.Env.REVISION}}
