// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"codeberg.org/pixivfe/pixivfe/server/template"
	"codeberg.org/pixivfe/pixivfe/server/template/commondata"
)

func Default(cd commondata.PageCommonData, title string, minimal bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		visualEffectsEnabled := cd.CookieList["pixivfe-VisualEffectsEnabled"] == "true"

		if title != "" {
			title = title + " - PixivFE"
		} else {
			title = "PixivFE"
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 23, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><meta name=\"description\" content=\"Read this on PixivFE\"><meta property=\"og:title\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 25, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><meta property=\"og:site_name\" content=\"PixivFE\"><meta property=\"og:type\" content=\"article\"><meta property=\"og:url\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(cd.CurrentPath)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 28, Col: 51}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\"><meta name=\"twitter:card\" content=\"summary_large_image\"><link rel=\"stylesheet\" href=\"/css/tailwind-style.css?hash=d30cabae\"><link href=\"/img/favicon.png\" rel=\"icon\"><link rel=\"manifest\" href=\"/manifest.json\"><meta name=\"htmx-config\" content=\"{&#34;defaultSettleDelay&#34;:0}\"><script src=\"/js/htmx@2.0.4.min.js\" integrity=\"sha512-2kIcAizYXhIn8TzUvqzEDZNuDZ+aW7yE/+f1HJHXFjQcGNfv1kqzJSTBRBSlOgp6B/KZsz1K0a3ZTqP9dnxioQ==\" defer></script><script src=\"/js/response-targets@2.0.3.min.js\" integrity=\"sha512-QzwJJs5KJujABALi59olWpdxbS/bnYLcC8d3L/CbVWbXVDXpon87/5q1Jl1xNrjS1xJ/LlAkmuWJnPLtGKSnyQ==\" defer></script><script src=\"/js/on-page-load.js\" defer></script><script src=\"/js/illust-preview.js\" defer></script></head><body class=\"group/body bg-neutral-900 text-neutral-100 fill-neutral-100 touch-manipulation subpixel-antialiased font-sans scheme-only-dark\n\t\t\t\t    has-[#imageExpand:checked]:overflow-hidden\n\t\t\t\t    has-[div:popover-open]:overflow-hidden\n\t\t\t\t    has-[div:popover-open]:not-[div:popover-open]:pointer-events-none\n\t\t\t\t    starting:opacity-80 opacity-100 transition duration-200 ease-out\n\t\t\t\t    selection:bg-white selection:text-black\" hx-boost=\"true\" hx-indicator=\"#loading-indicator\" hx-ext=\"response-targets\"><div id=\"loading-indicator\" class=\"fixed top-0 min-w-full h-1 z-999 duration-300 transition\n            bg-[80vw_auto]\n            animate-[rolling-something_1s_linear_infinite]\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !minimal {
			var templ_7745c5c3_Var5 = []any{templ.Classes(
				"fixed left-0 top-0 -z-1 w-full h-full",
				"transition-all transition-discrete duration-300",
				"hidden",
				"bg-black/0",
				"group-has-[.modal-popover:popover-open]/body:block",
				"group-has-[.modal-popover:popover-open]/body:starting:bg-black/0",
				"group-has-[.modal-popover:popover-open]/body:bg-black/60",
				"group-has-[.modal-popover:popover-open]/body:z-20",
				templ.KV("backdrop-blur-none", visualEffectsEnabled),
				templ.KV("group-has-[.modal-popover:popover-open]/body:starting:backdrop-blur-none", visualEffectsEnabled),
				templ.KV("group-has-[.modal-popover:popover-open]/body:backdrop-blur-[1px]", visualEffectsEnabled),
			)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var5...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div id=\"modalPopoverBackground\" class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var5).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = navbar(cd).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !minimal {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<main class=\"relative flex flex-col items-center min-h-screen px-4 py-20\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<main class=\"grid min-h-screen place-items-center p-4\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !minimal {
			templ_7745c5c3_Err = footer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = sidebar(cd).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = userMenu(cd).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = searchMenu().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func navbar(cd commondata.PageCommonData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		logoStyle := cd.CookieList["pixivfe-LogoStyle"]
		username := cd.CookieList["pixivfe-Username"]
		userID := cd.CookieList["pixivfe-UserID"]
		userAvatar := cd.CookieList["pixivfe-UserAvatar"]
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<nav class=\"fixed top-0 flex items-center justify-between h-14 w-full px-4 mx-auto bg-neutral-900 border-b border-neutral-700 z-10\"><div class=\"flex items-center gap-2\"><button popovertarget=\"sidebar\" class=\"flex items-center justify-center size-8 hover:bg-neutral-700 active:scale-95 transition rounded cursor-pointer text-neutral-300 hover:text-neutral-100\"><span class=\"material-symbols-rounded-24\">menu</span></button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if logoStyle == "" || logoStyle == "standard" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<a href=\"/\" class=\"text-xl font-medium animated-underline\">PixivFE</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if logoStyle == "alternative" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<a href=\"/\" class=\"size-8\"><img src=\"/img/logo-alt.gif\" alt=\"PixivFE icon\" class=\"size-full\"></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div><div class=\"flex items-center gap-4\"><button popovertarget=\"searchMenu\" class=\"flex items-center justify-center size-8 hover:bg-neutral-700 active:scale-95 transition rounded cursor-pointer text-neutral-300 hover:text-neutral-100 p-1\"><span class=\"material-symbols-rounded-24\">search</span></button> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if username != "" && userID != "" && userAvatar != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<div class=\"flex items-center gap-2\"><button popovertarget=\"userMenu\" class=\"flex fill-neutral-400 hover:fill-neutral-300 cursor-pointer transition\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(userAvatar)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 135, Col: 23}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" alt=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(username + "'s avatar")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 136, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\" class=\"w-8 rounded-full avatar-outline-glow\"></button></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 templ.SafeURL = templ.SafeURL("/self/login?noAuthReturnPath=" + cd.CurrentPath + "&loginReturnPath=" + cd.CurrentPath)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var10)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "\" class=\"group\"><div class=\"outlined-button text-sm font-medium gap-2\"><span class=\"material-symbols-rounded-20\">account_circle</span> Sign in</div></a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "<footer class=\"bg-neutral-900 border-t border-neutral-700 px-4\"><div class=\"h-full max-w-7xl py-8 mx-auto\"><div class=\"flex flex-col sm:flex-row justify-start sm:justify-between sm:items-end gap-8\"><div class=\"flex flex-col gap-2\"><div class=\"text-2xl font-medium\"><a href=\"/\" class=\"animated-underline\">PixivFE</a></div><div class=\"text-xs text-neutral-400\">An open-source alternative frontend for pixiv that doesn't suck.</div><div class=\"text-xs font-medium text-neutral-400\">Not developed, created, or distributed by pixiv.</div></div><div class=\"flex items-start gap-4\"><a href=\"https://htmx.org/\" rel=\"noopener\"><img class=\"w-48 sm:self-end\" src=\"/img/createdwith.jpeg\" width=\"680\" height=\"168\" loading=\"lazy\"></a></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func sidebar(cd commondata.PageCommonData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "<div popover id=\"sidebar\" class=\"fixed modal-popover pointer-events-none open:pointer-events-auto opacity-0 starting:open:opacity-0 open:opacity-100 transition-all transition-discrete duration-200 starting:open:-translate-x-full -translate-x-full open:translate-x-0 open:flex flex-col left-0 top-0 w-8/12 max-w-76 h-full overflow-y-auto bg-neutral-900 z-30\"><div class=\"sticky top-0 flex items-center justify-between w-full bg-neutral-900 border-b border-b-neutral-700 gap-24 py-3 px-4 z-4\"><a href=\"/\" class=\"flex w-fit text-xl font-medium animated-underline\">PixivFE</a> <button popovertarget=\"sidebar\" class=\"flex items-center justify-center size-8 cursor-pointer text-neutral-300 hover:text-neutral-100 hover:bg-neutral-700 active:scale-95 transition rounded-full p-1 -me-1\"><span class=\"material-symbols-rounded-24\">close</span></button></div><ul class=\"flex flex-col h-fit gap-y-5 py-3 px-4\"><div class=\"flex flex-col gap-1\"><li><a href=\"/discovery\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">explore</span> Discovery</a></li><li><a href=\"/ranking\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">leaderboard</span> Rankings</a></li><li><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var13 templ.SafeURL = templ.SafeURL("/self/followingWorks?noAuthReturnPath=" + cd.CurrentPath + "&loginReturnPath=/self/followingWorks")
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var13)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">article_person</span> Latest by followed users</a></li></div><div class=\"flex flex-col gap-1\"><div class=\"text-sm font-semibold text-neutral-400 mb-1\">Explore</div><li><a href=\"/rankingCalendar\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">calendar_month</span> Ranking calendar</a></li><li><a href=\"/newest\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(template.RenderIcon("bc517db2e1d069b87fd23a98cf50e0c20d531229", "bi bi-stars")).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "Newest</a></li><li><a href=\"/pixivision\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">palette</span> pixivision</a></li></div><div class=\"flex flex-col gap-1\"><div class=\"text-sm font-semibold text-neutral-400 mb-1\">You</div><li><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var14 templ.SafeURL = templ.SafeURL("/self?noAuthReturnPath=" + cd.CurrentPath)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var14)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">account_circle</span> Profile</a></li><li><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 templ.SafeURL = templ.SafeURL("/self/bookmarks?noAuthReturnPath=" + cd.CurrentPath)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var15)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">favorite</span> Bookmarks</a></li><li><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 templ.SafeURL = templ.SafeURL("/self/followingUsers?noAuthReturnPath=" + cd.CurrentPath)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var16)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">group</span> Followed users</a></li><li><a href=\"/settings\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-fill-20\">settings</span> Settings</a></li></div><div class=\"flex flex-col gap-1\"><div class=\"text-sm font-semibold text-neutral-400 mb-1\">Info</div><li><a href=\"/about\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">info</span> About</a></li><li><a href=\"https://codeberg.org/PixivFE/PixivFE\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 p-2 -mx-2\"><span class=\"material-symbols-rounded-20\">code</span> Source code</a></li></div></ul><div class=\"flex flex-col gap-1 text-neutral-400 bg-neutral-900 border-t border-t-neutral-700 px-4 py-3 sm:p-4 mt-auto z-4\"><div class=\"text-neutral-400 text-xs\">Revision</div><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 templ.SafeURL = templ.SafeURL(cd.RepoURL + "/commit/" + cd.RevisionHash)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var17)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "\" class=\"contents\"><div class=\"text-link text-neutral-300 hover:text-neutral-200 text-sm font-medium\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if cd.Revision != "" {
			var templ_7745c5c3_Var18 string
			templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(cd.Revision)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 334, Col: 19}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			var templ_7745c5c3_Var19 string
			templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs("unknown")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 336, Col: 17}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "</div></a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func userMenu(cd commondata.PageCommonData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var20 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var20 == nil {
			templ_7745c5c3_Var20 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		username := cd.CookieList["pixivfe-Username"]
		userID := cd.CookieList["pixivfe-UserID"]
		userAvatar := cd.CookieList["pixivfe-UserAvatar"]
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "<div popover id=\"userMenu\" class=\"peer pointer-events-none open:pointer-events-auto\n        opacity-0 starting:open:opacity-0 open:opacity-100 scale-95 starting:open:scale-95 open:scale-100 origin-top-right transition-all transition-discrete\n        open:flex flex-col h-fit w-72 bg-neutral-800 rounded-lg drop-shadow-lg mt-14 ms-auto me-4 z-30\"><div class=\"flex bg-neutral-700/40 gap-4 p-4\"><a href=\"/self\"><img src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var21 string
		templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(userAvatar)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 359, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "\" alt=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var22 string
		templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(username + "'s avatar")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 359, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "\" class=\"size-12 min-w-12 rounded-full avatar-outline-glow\"></a><div class=\"flex flex-col gap-1\"><a href=\"/self\"><div class=\"w-fit text-xl font-semibold text-neutral-200 hover:text-neutral-50 line-clamp-1 animated-underline\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 363, Col: 127}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</div></a><div class=\"flex text-xs text-neutral-400 gap-1\"><span class=\"font-medium\">User ID:</span><span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var24 string
		templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(userID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `assets/components/layout/stuff.templ`, Line: 366, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</span></div></div></div><ul class=\"flex flex-col w-full text-sm py-3 px-2 gap-1\"><li><a href=\"/self/bookmarks\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 px-4 py-3\"><span class=\"material-symbols-rounded-20\">favorite</span> Bookmarks</a></li><li><a href=\"/self/followingWorks\" class=\"flex items-center w-full hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 px-4 py-3\"><span class=\"material-symbols-rounded-20\">article_person</span> Latest by followed users</a></li><li><a href=\"/self/followingUsers\" class=\"flex items-center w-full hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 px-4 py-3\"><span class=\"material-symbols-rounded-20\">group</span> Followed users</a></li><li><a href=\"/settings\" class=\"flex items-center hover:text-neutral-50 hover:fill-neutral-50 hover:bg-neutral-700 rounded-lg text-neutral-300 fill-neutral-300 transition gap-2 px-4 py-3\"><span class=\"material-symbols-rounded-fill-20\">settings</span> Settings</a></li><li><form action=\"/settings/logout\" method=\"post\"><button type=\"submit\" class=\"flex items-center w-full cursor-pointer hover:bg-red-500/10 rounded-lg text-red-300 fill-red-300 transition gap-2 px-4 py-3\"><span class=\"material-symbols-rounded-20\">logout</span> Log out</button></form></li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func searchMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var25 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var25 == nil {
			templ_7745c5c3_Var25 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "<div popover id=\"searchMenu\" class=\"modal-popover pointer-events-none open:pointer-events-auto top-1/4 start-2/4 -translate-x-2/4 -translate-y-2/4\n        opacity-0 starting:open:opacity-0 open:opacity-100 scale-95 starting:open:scale-95 open:scale-100 transition-all transition-discrete\n        open:flex h-fit min-w-80 w-11/12 max-w-120 bg-neutral-900 border border-neutral-700 rounded-lg drop-shadow-lg z-30\"><div class=\"flex flex-col w-full gap-6 p-4\"><form action=\"/tags\" method=\"post\" autocomplete=\"off\"><div class=\"group relative flex items-center gap-4\"><span class=\"material-symbols-rounded-20 absolute start-2 text-neutral-500 group-has-[input:focus]:text-neutral-400 z-1\">search</span> <input type=\"search\" class=\"form-control w-full !px-8\" id=\"name\" name=\"name\" required autofocus placeholder=\"Search artworks\" aria-label=\"Search\"><button type=\"submit\" class=\"filled-button text-sm font-medium gap-2\"><span class=\"material-symbols-rounded-20\">arrow_forward</span>Go</button></div></form><div class=\"text-xs text-neutral-400 space-y-1 -mt-3\"><div>Delimit multiple keywords using spaces.</div><div><span class=\"font-medium\">Example:</span> <code class=\"bg-neutral-950\">東方project チルノ</code></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
